version: '3'

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    restart: always
    ports:
      - 3307:3307
    environment:
      MYSQL_DATABASE: map
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    build:
      context: php
    restart: always
    ports:
      - "9080:9000"
    volumes:
      - "./Economapas:/var/www/html"
    links:
      - mysql

  nginx:
    build:
      context: ./nginx
    volumes:
      - "./www:/var/www/html"
    ports:
      - "70:70"
    restart: always
    links:
      - php